travis:
  secure:
    BINSTAR_TOKEN: XgaBMIDijYDhGvnWar/nLPWpPdIMi7A3R4C9g5xwUN3sZd1fhhgvoo3aF4b6iCPsMiJml2ZN2gSEII3cbk8aiVRWtn02APWdwdMyjAlRCnXJkEd6XY87ct+9bQi/iTBUQebcSeNbIIBGgdWCqQlfFnadesyoLCCz/jIPR5YrOGKAwnt1KHrxa23LNma+QoUkX8Fky5FytQ+k43WDiqV+w0blYmkaGcUQkePthvfYj/VotabfK8dx71cujZeeePXEtBo+5hWlrPsrSFcDJgg/sSpcG/24s7o8W7HOTZ3v96/HijHciK/VXF1mFrrtAQhTgMVEYtUF6j7uL//cll1/ZHzX+xo9d2x3DgpK2PKNX6uk7ODEq7rrGc40i8sK+d46k67qL364XfhfjmAgp0wlqpRMmz1X0qNH0w3bC5rnLty7in38aV0xJ+ZLK4SbWcFRtDj2qx4VfiG4Onh+6caDTnNkLYXKEQ0TulJRwu3qLJXNECL7m+xo22tGDwCDyPKmN8+1dK3jhHD6paS5kKDlxrmgq/HJ4sLzDknKLeNyvOrqbIURiLEX1f1ivgOCtLxxZTVKGxIl55TXymBpMPgp0mGkU9qIATzma5HyPkhwhSaiWJMUfBovNKqRUwQFKmdq18BT25gGr1u3nYalVLeM/wiZFYtHcqJXtE+PcpeiozE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
